src/viper/Components/SidebarViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace viper.Components
{
    public class SidebarViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

src/viper/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace viper.Controllers
{
    public class AdminController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return RedirectToAction("Clients");
        }

        public ActionResult Clients()
        {
            return View();
        }

        public ActionResult Products()
        {
            return View("Clients");
        }
    }
}

src/viper/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Authorization;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace viper.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public ActionResult Users()
        {
            return View("Clients");
        }

        public ActionResult Clients()
        {
            return View();
        }

        public ActionResult Products()
        {
            return View("Clients");
        }

        public ActionResult Applications()
        {
            return View("Applications");
        }
    }
}

src/viper/Views/Shared/StatusCodePage.cshtml
@{
    ViewBag.Title = "Item not found";
}

<h1 class="text-danger">Item not found.</h1>
<h2 class="text-danger">Unable to find the item you are searching for. Please try again.</h2>

src/viper/Views/Shared/_AdminLayout.cshtml
@inject IOptions<AppSettings> AppSettings
@{
    Layout = "_Layout";
}

@functions
{
    string sidebarActiveCss(string action)
    {
        return action == ViewContext.RouteData.Values["action"].ToString() ?
            "active" : "";
    }
}

<div class="row wrapper" ng-app="viper">
    <ul class="nav nav-pills nav-stacked navbar-collapse collapse sidebar" ng-controller="sidebarController" >
        <li></li>
        <li role="presentation" class=" @sidebarActiveCss("Clients")"><a asp-controller="Admin" asp-action="Clients"><i class="fa fa-fw fa-male"></i> Clients</a></li>
        <li role="presentation" class=" @sidebarActiveCss("Products")"><a asp-controller="Admin" asp-action="Products"><i class="fa fa-fw fa-barcode"></i> Products</a></li>
    </ul>
    <div class="main">
        @RenderBody()
    </div>
</div>

src/viper/Views/Shared/_BodyScriptsPartial.cshtml
@inject IOptions<AppSettings> AppSettings

<environment names="Development">
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/hammer.js/hammer.js"></script>
    <script src="~/lib/angular/angular.js"></script>
    <script src="~/lib/bluebird/js/browser/bluebird.js"></script>
    <script src="~/lib/angular-smart-table/dist/smart-table.js"></script>
    <script src="~/lib/angular-bootstrap/ui-bootstrap-tpls.js"></script>
    <script src="~/lib/angular-mocks/angular-mocks.js"></script>
    <script src="~/lib/notifyjs/dist/notify.js"></script>
    <script src="~/static-libs/countUp.js/dist/angular-countUp.js"></script>
    <script src="~/lib/angular-loading-bar/build/loading-bar.js"></script>
    <script src="~/lib/checklist-model/checklist-model.js"></script>
    <script src="~/lib/lodash/lodash.js"></script>
    <script src="~/dist/app.js"></script>
</environment>
<environment names="Staging,Production">
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.10.2/jquery.min.js"
            asp-fallback-test="window.jQuery">
    </script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"
            asp-fallback-test="window.bootstrap">
    </script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.4/hammer.min.js"
            asp-fallback-test="window.Hammer">
    </script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.min.js"
            asp-fallback-test="window.angular">
    </script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/bluebird/3.0.5/bluebird.min.js"></script>
    <script src="~/lib/angular-smart-table/dist/smart-table.min.js"></script>
    <script src="~/lib/angular-bootstrap/ui-bootstrap-tpls.min.js"></script>
    <script src="~/lib/angular-mocks/angular-mocks.js"></script>
    <script src="~/lib/notifyjs/dist/notify.js"></script>
    <script src="~/static-libs/countUp.js/dist/angular-countUp.min.js"></script>
    <script src="~/lib/angular-loading-bar/build/loading-bar.min.js"></script>
    <script src="~/lib/checklist-model/checklist-model.js"></script>
    <script src="~/lib/lodash/lodash.min.js"></script>
    <script src="~/dist/app.min.js"></script>
</environment>

src/viper/Views/Shared/_DashboardLayout.cshtml
@using viper.Components
@inject IOptions<AppSettings> AppSettings
@{
    Layout = "_Layout";
}
<div class="container-fluid main">
    <div class="row">
        @await Component.InvokeAsync("Sidebar")
        <div id="page-wrapper">
            @RenderBody()
        </div>
    </div>
</div>

@section scripts {
    @RenderSection("scripts", required: false)
}

src/viper/Views/Shared/_HeadPartial.cshtml
@inject IOptions<AppSettings> AppSettings
@inject viper.Services.Session Session

<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="Expires" content="-1">
<meta http-equiv="pragma" content="no-cache" />
<title>@Session.SiteTitle</title>

<environment names="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-touch-carousel/dist/css/bootstrap-touch-carousel.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css">
    <link rel="stylesheet" href="~/lib/datatables/media/css/dataTables.bootstrap.css" />
    <link rel="stylesheet" href="~/lib/angular-loading-bar/build/loading-bar.css" />
</environment>
<environment names="Staging,Production">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css" />
    <link rel="stylesheet" href="~/lib/datatables/media/css/dataTables.bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/angular-loading-bar/build/loading-bar.min.css" />
</environment>
<link rel="stylesheet" href="~/css/header.css" />
<link rel="stylesheet" href="~/css/dashboard.css" />
<link rel="stylesheet" href="~/css/sb-admin.css" />

src/viper/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@inject IOptions<AppSettings> AppSettings
@inject viper.Services.Session Session
<!DOCTYPE html>
<html ng-app="viper">
    <head>
        @await Html.PartialAsync("_HeadPartial")
        @RenderSection("styles", required: false)
    </head>
    <body>
        <nav class="header">
            <div class="header-left">
                <a class="header-brand" asp-controller="Dashboard" asp-action="Index">
                    Viper Admin
                </a>
            </div>
            <div class="header-right">
                @await Html.PartialAsync("_LoginPartial")
            </div>
</nav>
        @RenderBody()
        <div class="scripts">
            @await Html.PartialAsync("_BodyScriptsPartial")
            @RenderSection("scripts", required: false)
        </div>
    </body>
</html>

src/viper/Views/Shared/_MenulessLayout.cshtml
@inject IOptions<AppSettings> AppSettings
<!DOCTYPE html>
<html>
    <head>
        @await Html.PartialAsync("_HeadPartial")
        @RenderSection("styles", required: false)
    </head>
    <body>
        @RenderBody()
        @await Html.PartialAsync("_BodyScriptsPartial")
        @RenderSection("scripts", required: false)
    </body>
</html>